-- return {
--   -- Package manager for LSP servers
--   "williamboman/mason.nvim",
--   cmd = "Mason",
--   build = ":MasonUpdate",
--   opts = {
--     ensure_installed = {
--       "rust-analyzer", -- rust
--       "lua-language-server", -- lua
--       "terraform-ls", -- terraform
--       "taplo", -- toml
--       "json-lsp", -- json
--       "ruff",
--       "pyright",
--       "mypy",
--       "vtsls",
--     },
--   },
--   config = function(_, opts)
--     require("mason").setup(opts)
--     local mr = require("mason-registry")
--     local function ensure_installed()
--       for _, tool in ipairs(opts.ensure_installed) do
--         local p = mr.get_package(tool)
--         if not p:is_installed() then
--           p:install()
--         end
--       end
--     end
--     if mr.refresh then
--       mr.refresh(ensure_installed)
--     else
--       ensure_installed()
--     end
--   end,
-- }
