#!/bin/bash
#
# discord startup sequencer -- launched at login by dev.ayu.discord-startup
# canary comes up first, then stable follows 30s later. both open in the
# background (open -g) so neither steals focus mid-login
#
# macos "reopen after restart" (resume) relaunches whatever was running -- in its
# own order, with no delay -- which would race our ordering. so we first quit any
# discord that resume (or anything else) already brought back, wait for it to
# fully exit, then relaunch canary -> stable ourselves. deterministic even with
# resume on. cost: a brief relaunch flicker and discord's restored windows reset
#
# the launchd plist (~/Library/LaunchAgents/dev.ayu.discord-startup.plist) is
# generated by ../discord-startup.sh and points straight at this file, so you can
# tweak the apps or the delay here and just log out/in, no reinstall
#
# heads up: turn OFF "open discord" in each client (user settings -> windows
# settings) or macos will auto-launch them too and you get a double start

set -u

# app names as launchservices/applescript see them; override delays via env
CANARY="Discord Canary"
STABLE="Discord"
DELAY="${DISCORD_STARTUP_DELAY:-30}"
QUIT_TIMEOUT="${DISCORD_QUIT_TIMEOUT:-15}"
# resume and this agent race at login; wait a beat so resume's relaunches exist
# to be caught below. set to 0 if you never use reopen-after-restart
SETTLE="${DISCORD_STARTUP_SETTLE:-3}"

# true if the named app has a live process. querying `running` does NOT launch
# the app -- one of applescript's few no-launch properties
is_running() {
  [[ "$(osascript -e "application \"$1\" is running" 2>/dev/null)" == "true" ]]
}

# quit the app only if it is actually up (else applescript would launch it just
# to quit it), then wait until it lets go. discord's single-instance lock means a
# too-early relaunch would just poke the dying instance instead of starting fresh
quit_and_wait() {
  local app="$1" waited=0
  is_running "$app" || return 0
  echo "discord-startup: quitting '$app' (resume relaunch)"
  osascript -e "tell application \"$app\" to quit" 2>/dev/null || true
  while is_running "$app" && (( waited < QUIT_TIMEOUT )); do
    sleep 1
    waited=$((waited + 1))
  done
  if is_running "$app"; then
    echo "discord-startup: '$app' still up after ${QUIT_TIMEOUT}s; relaunching anyway" >&2
  fi
}

launch() {
  local app="$1"
  if open -g -a "$app"; then
    echo "discord-startup: launched '$app'"
  else
    echo "discord-startup: could not launch '$app'" >&2
  fi
}

# let resume finish, then clear whatever it relaunched so the order below wins
sleep "$SETTLE"
quit_and_wait "$CANARY"
quit_and_wait "$STABLE"

launch "$CANARY"
sleep "$DELAY"
launch "$STABLE"
