#!/bin/bash
#
# discord startup sequencer -- launched at login by dev.ayu.discord-startup
# canary comes up first, then stable follows 30s later. both open in the
# background (open -g) so neither steals focus mid-login
#
# the launchd plist (~/Library/LaunchAgents/dev.ayu.discord-startup.plist) is
# generated by ../discord-startup.sh and points straight at this file, so you
# can tweak the apps or the delay here and just log out/in, no reinstall
#
# heads up: turn OFF "open discord" in each client (user settings -> windows
# settings) or macos will auto-launch them too and you get a double start

set -u

# app names as launchservices sees them; override the delay via env if wanted
CANARY="Discord Canary"
STABLE="Discord"
DELAY="${DISCORD_STARTUP_DELAY:-30}"

launch() {
  local app="$1"
  if open -g -a "$app"; then
    echo "discord-startup: launched '$app'"
  else
    echo "discord-startup: could not launch '$app'" >&2
  fi
}

launch "$CANARY"
sleep "$DELAY"
launch "$STABLE"
